### ISSUE TITLE
Upload project fails

### ISSUE THREAD

**Issue by retorquere** [danthareja/node-google-apps-script#16]
I've been able to init and download, but upload fails. I've tried `gaps upload` both in my git project and in the subdirectory in it that has the GAS scripts. If I try in the git directory, I get:

```
Pushing /home/emile/github/DoCMS back up to Google Drive...
Error running upload command { [Error: ENOENT, open '/home/emile/github/DoCMS/.manifest.json']
  errno: 34,
  code: 'ENOENT',
  path: '/home/emile/github/DoCMS/.manifest.json' }
```

if I try in the GAS subdir created by the download action, I get

```
Pushing /home/emile/github/DoCMS/DoCMS back up to Google Drive...

/home/emile/github/DoCMS/node_modules/node-google-apps-script/lib/utils/manifestor.js:18
      file = path.parse(filename);
                  ^
TypeError: Object #<Object> has no method 'parse'
    at /home/emile/github/DoCMS/node_modules/node-google-apps-script/lib/utils/manifestor.js:18:19
    at /home/emile/github/DoCMS/node_modules/node-google-apps-script/node_modules/node-dir/lib/readfiles.js:99:34
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by danthareja** [comment]
This seems like a node issue, `path.parse` was introduced in v0.12. What version are you running? You can check with `node -v`

**Comment by retorquere** [comment]
Ah, that was it, I was still on 0.10, Ubuntu lags terribly behind. I've
upgraded, and the problem went away.

**Comment by danthareja** [comment]
Excellent!
