### ISSUE TITLE
Error on gapps push

### ISSUE THREAD

**Issue by ZocaLoans** [danthareja/node-google-apps-script#25]
I get the following error when trying to gapps push:

```
> gapps push
Pushing back up to Google Drive...

/usr/local/lib/node_modules/node-google-apps-script/lib/util.js:18
        file = path.parse(filename);
                    ^
TypeError: Object #<Object> has no method 'parse'
    at /usr/local/lib/node_modules/node-google-apps-script/lib/util.js:18:21
    at /usr/local/lib/node_modules/node-google-apps-script/node_modules/node-dir/lib/readfiles.js:110:34
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

**Comment by ZocaLoans** [comment]
Never mind. Saw this address in a closed ticket.
