### ISSUE TITLE
gapps init throws error if there is .json manifest file in the project

### ISSUE THREAD

**Issue by vikdet** [danthareja/node-google-apps-script#58]
Because of Gmail add-ons project has appsmanifest.json file I faced with the following issue:

1. Create an empty Gmail add-ons project.
2. Click View -> Show manifest file
3. execute gapps init 'project_id'
4. See an error: 
`Error running init command
Unhandled rejection Error: Unsupported file type found
    at Object.getFileExtension (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/lib/util.js:60:9)
    at writeExternalFile (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/lib/commands/init.js:48:35)
    at /home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/lib/commands/init.js:39:14
    at tryCatcher (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/map.js:56:38)
    at MappingPromiseArray.init (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/promise_array.js:92:18)
    at Promise._settlePromiseAt (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vitalybevzik/.nvm/versions/node/v5.12.0/lib/node_modules/node-google-apps-script/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
`

**Comment by vikdet** [comment]
MR to resolve this https://github.com/danthareja/node-google-apps-script/pull/59/files

**Comment by vietnogi** [comment]
Currently, gapps will delete .json files on google drive.  I think this fix will also prevent said problem.

**Comment by lricoy** [comment]
Fixed by #73
