### ISSUE TITLE
Can't initialize project

### ISSUE THREAD

**Issue by alexwforsythe** [danthareja/node-google-apps-script#64]
1. `node -v`: `v0.12.18`
2. `npm -v`: `2.15.11`
3. `npm install -g node-google-apps-script`
4. `gapps init ${fileId}`:

```
Object.assign(exports, dirpaths)
       ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/alexf/.nvm/versions/node/v0.12.18/lib/node_modules/node-google-apps-script/node_modules/node-dir/index.js:3:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/alexf/.nvm/versions/node/v0.12.18/lib/node_modules/node-google-apps-script/lib/util.js:2:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/alexf/.nvm/versions/node/v0.12.18/lib/node_modules/node-google-apps-script/lib/manifestor.js:9:12)
    at Module._compile (module.js:460:26)
```

Am I doing something wrong?

**Comment by lricoy** [comment]
Hey @alexwforsythe  Would a newer node version work for you? (maybe `lts/carbon - v8.9.1`?) I am aware that the requirements on the README says node `v0.12.x` is a requirement but hopefully we will be able to upgrade it soon.  Will close this one but please reopen if needed
