### ISSUE TITLE
Installation fails with yarn global

### ISSUE THREAD

**Issue by aymericbouzy** [danthareja/node-google-apps-script#69]
I ran `yarn global add node-google-apps-script`
and got in return
```
yarn global v1.1.0
[1/4] 🔍  Resolving packages...
warning node-uuid@1.4.8: Use uuid module instead
warning node-uuid@1.4.8: Use uuid module instead
warning tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "nesh@1.7.0" has unmet peer dependency "coffee-script@>=1.6.2 <2".
[4/4] 📃  Building fresh packages...
[-/3] ⠁ waiting...
[2/3] ⠁ v8-debug: Failed to execute '/Users/aymericbouzy/.nvm/versions/node/v8.6.0/bin/node /Users/aymericbouzy/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js bu
[3/3] ⠁ v8-profiler: CXX(target) Release/obj.target/profiler/src/profiler.o
[-/3] ⠁ waiting...
error /Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.38
node-pre-gyp info using node@8.6.0 | darwin | x64
node-pre-gyp info check checked for "/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.6.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.6.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.6.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/aymericbouzy/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aymericbouzy/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aymericbouzy/.node-gyp/8.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/aymericbouzy/.node-gyp/8.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/aymericbouzy/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/aymericbouzy/.node-gyp/8.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.6.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:41:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        v8::Debug::Call(context, fn);
                   ^
/Users/aymericbouzy/.node-gyp/8.6.0/include/node/v8-debug.h:193:42: note: 'Call' has been explicitly marked deprecated here
                static MaybeLocal<Value> Call(
                                         ^
../src/debug.cc:52:45: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Isolate* debug_isolate = v8::Debug::GetDebugContext(Isolate::GetCurrent())->GetIsolate();
                                            ^
/Users/aymericbouzy/.node-gyp/8.6.0/include/node/v8-debug.h:209:39: note: 'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext(Isolate* isolate));
                                      ^
../src/debug.cc:57:20: warning: 'SendCommand' is deprecated [-Wdeprecated-declarations]
        v8::Debug::SendCommand(debug_isolate, *command, command.length());
                   ^
/Users/aymericbouzy/.node-gyp/8.6.0/include/node/v8-debug.h:170:29: note: 'SendCommand' has been explicitly marked deprecated here
                static void SendCommand(Isolate* isolate,
                            ^
../src/debug.cc:71:51: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Local<Context> debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                                  ^
/Users/aymericbouzy/.node-gyp/8.6.0/include/node/v8-debug.h:209:39: note: 'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext(Isolate* isolate));
                                      ^
../src/debug.cc:78:22: error: no member named 'GetMirror' in 'v8::Debug'
          v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext(), info[0]);
          ~~~~~~~~~~~^
../src/debug.cc:80:38: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
          debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                     ^
/Users/aymericbouzy/.node-gyp/8.6.0/include/node/v8-debug.h:209:39: note: 'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext(Isolate* isolate));
                                      ^
5 warnings and 1 error generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aymericbouzy/.config/yarn/global/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/aymericbouzy/.nvm/versions/node/v8.6.0/bin/node" "/Users/aymericbouzy/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64"
gyp ERR! cwd /Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/aymericbouzy/.nvm/versions/node/v8.6.0/bin/node /Users/aymericbouzy/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aymericbouzy/.config/yarn/global/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/aymericbouzy/.nvm/versions/node/v8.6.0/bin/node" "/Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/aymericbouzy/.config/yarn/global/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
```

**Comment by aymericbouzy** [comment]
running `npm install -g node-google-apps-script` succeeds.
